// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks(id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id, completed
`

type CreateTaskParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Body, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Completed,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, created_at, updated_at, body, user_id, completed FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Completed,
	)
	return i, err
}

const getTasksByUserID = `-- name: GetTasksByUserID :many
SELECT id, created_at, updated_at, body, user_id, completed FROM tasks
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetTasksByUserID(ctx context.Context, userID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskBody = `-- name: UpdateTaskBody :one
UPDATE tasks
SET body = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, body, user_id, completed
`

type UpdateTaskBodyParams struct {
	ID   uuid.UUID
	Body string
}

func (q *Queries) UpdateTaskBody(ctx context.Context, arg UpdateTaskBodyParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskBody, arg.ID, arg.Body)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Completed,
	)
	return i, err
}

const updateTaskCompletedStatus = `-- name: UpdateTaskCompletedStatus :one
UPDATE tasks
SET completed = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, body, user_id, completed
`

type UpdateTaskCompletedStatusParams struct {
	ID        uuid.UUID
	Completed bool
}

func (q *Queries) UpdateTaskCompletedStatus(ctx context.Context, arg UpdateTaskCompletedStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskCompletedStatus, arg.ID, arg.Completed)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Completed,
	)
	return i, err
}
